<template>
    <div v-if="src" :style="{ height: `${desiredHeight}px` }" class="relative">
        <img
            @click.right.prevent="showImageToolbar = !showImageToolbar"
            :src
            alt="An image generated by the replicator."
            class="h-full w-full object-cover"
            :class="[imgClasses]"
        />
        <form v-if="showImageToolbar" @submit.prevent="reset">
            <Card class="absolute right-0 top-full mt-2" id="toolbar-img">
                <DangerButton type="submit">Reset</DangerButton>
            </Card>
        </form>
    </div>
    <form
        v-else
        @submit.prevent="submit"
        class="group relative flex border border-dashed border-primary"
    >
        <div ref="target" class="h-full w-full">
            <TextArea
                v-model="prompt"
                class="flex min-h-20 w-full resize-y !ring-0 transition-none focus:ring-0"
                :rows="1"
                :placeholder
            ></TextArea>
        </div>
        <Card class="absolute right-0 top-full mt-2" id="toolbar-form">
            <SecondaryButton type="submit">Generate</SecondaryButton>
        </Card>
    </form>
</template>

<script setup>
import TextArea from "@/Components/TextArea.vue";
import { onBeforeMount, ref } from "vue";
import SecondaryButton from "@/Components/SecondaryButton.vue";
import Card from "@/Components/Card.vue";
import DangerButton from "@/Components/DangerButton.vue";

const props = defineProps({
    identifier: {
        type: String,
        required: true,
    },
    src: {
        type: String,
    },
    imgClasses: {
        type: String,
        default: "",
    },
    placeholder: {
        type: String,
        default: "Enter a prompt to generate an image…",
    },
});

if (!props.identifier) {
    alert(
        "For the ImageReplicator to work correctly, you must provide a hardcoded, unique identifier.",
    );
}

const sizes = [
    { name: "1024x1024", value: 1024 / 1024 },
    { name: "1024x1792", value: 1024 / 1792 },
    { name: "1792x1024", value: 1792 / 1024 },
];

const target = ref(null);
const showImageToolbar = ref(false);

const prompt = ref("");
const desiredHeight = ref(0);

onBeforeMount(() => {
    if (props.src) {
        const parts = props.src.split(".");
        desiredHeight.value = parseInt(parts[parts.length - 2]);
    }
});

const actualSize = () => target.value.getBoundingClientRect();

const closestSupportedRatio = () => {
    const boundingBox = actualSize();
    const ratio = boundingBox.width / boundingBox.height;

    desiredHeight.value = boundingBox.height;

    return sizes.reduce((prev, curr) =>
        Math.abs(curr.value - ratio) < Math.abs(prev.value - ratio)
            ? curr
            : prev,
    ).name;
};

const submit = async () => {
    await axios.post(route("api.holodeck.image-replicator.store"), {
        identifier: props.identifier,
        prompt: prompt.value,
        size: closestSupportedRatio(),
        desiredHeight: actualSize().height,
    });
};

const reset = async () => {
    showImageToolbar.value = false;

    await axios.delete(
        route("api.holodeck.image-replicator.delete", props.identifier),
    );
};
</script>

<style scoped>
form:not(:focus-within) #toolbar-form {
    visibility: hidden;
}
</style>
